name: Test and Deploy Lambda
on: [push]
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          lambda-name: [my-go-function]
          binary-name: [bootstrap]
      steps:
        - uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.21
        - name: Build
          run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ${{matrix.binary-name}} -v main.go
        - name: Zip
          run: zip -j deploy.zip ${{matrix.binary-name}}
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2
        - name: Upload Zip
          run: aws lambda update-function-code --function-name ${{matrix.lambda-name}} --zip-file fileb://deploy.zip