name: Test and Deploy Lambda
on: [push]
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          lambda-name: [my-go-function]
          binary-name: [bootstrap]
          language: ['go']
          go-version: ['1.21.x']
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.21
        
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v2
          with:
            languages: ${{ matrix.language }}
        
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v2
          with:
            category: "/language:${{matrix.language}}"
        
        - name: Test with Go
          run: |
            go install github.com/jstemmer/go-junit-report@latest
            go test -v | go-junit-report -set-exit-code > report.xml
        
        - name: Upload Go test results
          uses: test-summary/action@v2
          if: ${{ always() }}
          with:
            paths: "report.xml"

        - name: Build
          run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ${{matrix.binary-name}} -v main.go

        - name: Zip
          run: zip -j deploy.zip ${{matrix.binary-name}}

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2

        - name: Upload Zip
          run: aws lambda update-function-code --function-name ${{matrix.lambda-name}} --zip-file fileb://deploy.zip